version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - pip install --user aws-sam-cli --no-warn-script-location
      - USER_BASE_PATH=$(python -m site --user-base)
      - export PATH=$PATH:$USER_BASE_PATH/bin
      - cd alexa-gateway
      - npm install
      - cd ..
  build:
    commands:
      - cd alexa-gateway
      - npm run build
      - AWS_ACCESS_KEY_ID=testKey AWS_SECRET_ACCESS_KEY=testSecretKey npm run test
      - cd ..
      - sam build
      - sam package --s3-bucket $S3BUCKET --s3-prefix $S3PREFIX --output-template-file packaged.yml
artifacts:
  type: zip
  files:
    - template.yml
    - packaged.yml